name: Daily Workflow

on:
  schedule:
    - cron:"*/45 * * * *# Ejecutar todos los días a las 02:00 AM UTC "*/15 * * * *" '0 2 * * *'

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute script
        run: python scrapper_gpt_copilot.py
      - name: Commit changes
        run: |
          msg="Updated: `date +'%Y-%m-%d %H:%M'`"
          git config --global user.email "facundo.toneguzzo@gmail.com"
          git config --global user.name "fcdata"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "$msg"
          git push
