name: Daily Workflow

on:
  schedule:
    - cron: "*/15 * * * *" # Ejecutar cada 15 minutos

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SCRAPPER_SECRET_GITHUB }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Data directory existe & execute script 
        run: |
          mkdir -p data
          python scrapper_gpt_copilot.py
      - name: Commit changes
        run: |
          msg="Updated: `date +'%Y-%m-%d %H:%M'`"
          git config --global user.email "facundo.toneguzzo@gmail.com"
          git config --global user.name "fcdata"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "$msg"
          git push
