name: scrap - Workflow 

on:
  schedule:
    - cron: "0 */3 * * *" # Ejecutar cada 3 horas
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SCRAPPER_SECRET_GITHUB }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Path settings
        run: |
          export PYTHONPATH="${{ github.workspace }}/src/module:${{ github.workspace }}/src:${{ github.workspace }}"

      - name: Data directory exist & execute script 
        run: |
          mkdir -p data/raw/2024
          python src/scrap.py

      - name: Commit changes
        run: |
          git config --global user.email "facu_mt@hotmail.com"
          git config --global user.name "fcdata"
          git pull origin main
          git add data/
          git diff --cached --exit-code || git commit -m "Updated: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push || echo "No changes to push"
